/**
 * NIHOMI.COM — Mock Data
 */
import { DashboardApiResponse } from './types';

export const mockDashboardData: DashboardApiResponse = {
  student: {
    id: 'usr_nihomi_demo_01',
    name: 'Tanvir',
    jlptLevel: 'N5',
    journeyDay: 27,
    learningStatusMessage: 'On track for December JLPT',
    learningStatusMessageBn: 'আজকের দৈনিক লক্ষ্য পূরণ করতে আরও ২০ মিনিট প্রয়োজন',
  },
  continueLesson: {
    lessonId: 'les_n5_012',
    lessonNumber: 12,
    title: 'Essential Particles',
    topic: 'Particles: は / が (Topic vs Subject)',
    topicJapanese: '助詞：は・がの使い方',
    jlptLevel: 'N5',
    progressPercent: 68,
    estimatedMinutesLeft: 12,
  },
  dailyPlan: [
    {
      id: 'dp_1',
      title: 'Vocabulary: Daily Actions',
      titleBangla: 'শব্দভাণ্ডার: দৈনন্দিন কাজ (১৫টি শব্দ)',
      type: 'vocabulary',
      status: 'completed',
      detail: '15 / 15 words reviewed',
    },
    {
      id: 'dp_2',
      title: 'Grammar: Particle は vs が',
      titleBangla: 'ব্যাকরণ: は এবং が এর পার্থক্য',
      type: 'grammar',
      status: 'completed',
      detail: 'Quiz score 90%',
    },
    {
      id: 'dp_3',
      title: 'Listening: Convenience Store Dialogue',
      titleBangla: 'শ্রবণ অনুশীলন: কনভেনিয়েন্স স্টোর কথোপকথন',
      type: 'listening',
      status: 'in_progress',
      detail: 'Audio clip (2:40 min)',
    },
    {
      id: 'dp_4',
      title: 'N5 Daily Challenge',
      titleBangla: 'দৈনিক চ্যালেঞ্জ: ৫টি দ্রুত প্রশ্ন',
      type: 'challenge',
      status: 'pending',
      detail: '5 questions • +20 XP',
    },
  ],
  dailyChallenge: {
    id: 'ch_2026_09_04',
    title: 'N5 Daily Speed Quiz',
    titleJapanese: '今日の５問チャレンジ',
    questionCount: 5,
    xpReward: 20,
    coinReward: 5,
    currentStreak: 6,
    isCompleted: false,
    status: 'available',
  },
  jlptProgress: {
    level: 'N5',
    overallPercent: 46,
    modules: {
      vocabulary: 54,
      grammar: 48,
      kanji: 42,
      listening: 38,
      reading: 35,
    },
  },
  streak: {
    currentStreak: 12,
    bestStreak: 18,
    weeklyActivity: [
      { dayName: 'Sat', dayNameBn: 'শনি', dateStr: '29 Aug', completed: true, isToday: false },
      { dayName: 'Sun', dayNameBn: 'রবি', dateStr: '30 Aug', completed: true, isToday: false },
      { dayName: 'Mon', dayNameBn: 'সোম', dateStr: '31 Aug', completed: true, isToday: false },
      { dayName: 'Tue', dayNameBn: 'মঙ্গল', dateStr: '01 Sep', completed: true, isToday: false },
      { dayName: 'Wed', dayNameBn: 'বুধ', dateStr: '02 Sep', completed: true, isToday: false },
      { dayName: 'Thu', dayNameBn: 'বৃহঃ', dateStr: '03 Sep', completed: true, isToday: false },
      { dayName: 'Fri', dayNameBn: 'শুক্র', dateStr: '04 Sep', completed: false, isToday: true },
    ],
  },
  recentMistakes: [
    {
      id: 'mstk_1',
      pattern: 'は vs が',
      patternJapanese: 'わたしは vs わたしが',
      category: 'particle',
      missedCount: 3,
      lastMissed: 'Yesterday',
      hintBn: 'সাধারণ বিষয় বোঝাতে は, নতুন বা নির্দিষ্ট তথ্য জোর দিতে が ব্যবহৃত হয়।',
    },
    {
      id: 'mstk_2',
      pattern: 'に vs で',
      patternJapanese: 'いえに vs いえで',
      category: 'particle',
      missedCount: 2,
      lastMissed: '2 days ago',
      hintBn: 'অবস্থান নির্দেশ করতে に, কোনো কাজ সম্পাদনের স্থান বোঝাতে で।',
    },
    {
      id: 'mstk_3',
      pattern: 'です vs ます',
      patternJapanese: 'がくせいです vs たべます',
      category: 'politeness',
      missedCount: 2,
      lastMissed: '3 days ago',
      hintBn: 'বিশেষ্য/বিশেষণে です, ক্রিয়াপদের মার্জিত রূপ তৈরিতে ます বসে।',
    },
  ],
  vocabularyProgress: { completed: 342, total: 800 },
  kanjiProgress: { completed: 87, total: 120 },
  accountUsage: { aiCreditsRemaining: 85, aiCreditsMax: 100, nihomiCoins: 420 },
};

export const mockEmptyDashboardData: DashboardApiResponse = {
  student: {
    id: 'usr_new_001',
    name: 'New Student',
    jlptLevel: 'N5',
    journeyDay: 1,
    learningStatusMessage: 'Start your journey today',
    learningStatusMessageBn: 'আপনার প্রথম জাপানিজ লেসন শুরু করুন',
  },
  continueLesson: null,
  dailyPlan: [],
  dailyChallenge: null,
  jlptProgress: {
    level: 'N5',
    overallPercent: 0,
    modules: { vocabulary: 0, grammar: 0, kanji: 0, listening: 0, reading: 0 },
  },
  streak: {
    currentStreak: 0,
    bestStreak: 0,
    weeklyActivity: [
      { dayName: 'Sat', dayNameBn: 'শনি', dateStr: '', completed: false, isToday: false },
      { dayName: 'Sun', dayNameBn: 'রবি', dateStr: '', completed: false, isToday: false },
      { dayName: 'Mon', dayNameBn: 'সোম', dateStr: '', completed: false, isToday: false },
      { dayName: 'Tue', dayNameBn: 'মঙ্গল', dateStr: '', completed: false, isToday: false },
      { dayName: 'Wed', dayNameBn: 'বুধ', dateStr: '', completed: false, isToday: false },
      { dayName: 'Thu', dayNameBn: 'বৃহঃ', dateStr: '', completed: false, isToday: false },
      { dayName: 'Fri', dayNameBn: 'শুক্র', dateStr: '', completed: false, isToday: true },
    ],
  },
  recentMistakes: [],
  vocabularyProgress: { completed: 0, total: 800 },
  kanjiProgress: { completed: 0, total: 120 },
  accountUsage: { aiCreditsRemaining: 100, aiCreditsMax: 100, nihomiCoins: 50 },
};