// src/views/MemoryOsView.tsx
import React, { useState } from 'react';
import {
  BookOpen,
  Download,
  Sparkles,
  Printer,
  FileText,
  AlertCircle,
  CheckCircle2,
  Layers,
  Calendar,
  Award,
  Zap,
  ArrowRight,
  ShieldCheck
} from 'lucide-react';
import jsPDF from 'jspdf';
import { useAuth } from '../context/AuthContext';

interface MemoryOsViewProps {
  onNavigate: (view: string, params?: Record<string, any>) => void;
}

export const MemoryOsView: React.FC<MemoryOsViewProps> = ({ onNavigate }) => {
  const { user, profile, progress } = useAuth();
  const [isGenerating, setIsGenerating] = useState(false);
  const [activeTab, setActiveTab] = useState<'preview' | 'dna_stats'>('preview');

  // Simulated dynamic learning memory analysis for current student
  const studentName = profile?.displayName || 'Tanvir Kabir Biplob';
  const targetLevel = profile?.targetLevel || 'N5';
  const memoryId = `NHM-MEM-${targetLevel}-2026-0814`;

  const weakKanji = [
    { char: '曜', reading: 'よう (you)', meaning: 'Day of week', errorRate: '42% error in drills', tip: 'Notice the 日 (sun) radical on the left and 羽 (feathers) at the top!' },
    { char: '食', reading: 'た・しょく', meaning: 'Eat / Food', errorRate: '35% confusion with 飲', tip: 'Think of a roof over a bowl of food.' },
    { char: '語', reading: 'ご (go)', meaning: 'Language', errorRate: '28% radical mistake', tip: 'Combines 言 (words) + 五 (five) + 口 (mouth).' }
  ];

  const repeatedMistakes = [
    {
      topic: 'Particle を vs に with Motion Verbs',
      failedSentence: '公園を行きます (Incorrect)',
      correctedSentence: '公園に行きます (Correct)',
      rule: 'Direction of destination always takes に (ni) or へ (e), while direct objects take を (o).'
    },
    {
      topic: 'Te-Form Conjugation for Group 1 (Godan Verbs)',
      failedSentence: '飲みて (Incorrect)',
      correctedSentence: '飲んで (Correct - nonde)',
      rule: 'Verbs ending in ~mu, ~bu, ~nu conjugate to ~nde (e.g. nomu -> nonde).'
    },
    {
      topic: 'Giving & Receiving (あげる vs くれる)',
      failedSentence: '先生は私に本をあげました (Incorrect)',
      correctedSentence: '先生は私に本をくれました (Correct)',
      rule: 'When someone gives something TO ME, always use くれる (kureru), never あげる (ageru).'
    }
  ];

  const handleDownloadPDF = () => {
    setIsGenerating(true);
    try {
      const doc = new jsPDF({
        orientation: 'portrait',
        unit: 'mm',
        format: 'a5' // A5 Pocketbook Format
      });

      const pageWidth = doc.internal.pageSize.getWidth();

      // Cover Page
      doc.setFillColor(12, 24, 43); // Midnight Navy
      doc.rect(0, 0, pageWidth, 210, 'F');

      doc.setFillColor(188, 44, 61); // Crimson Accent
      doc.rect(0, 0, pageWidth, 5, 'F');

      // Title
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('NIHOMI MEMORYOS™ • PURPLE COW EDITION', 15, 25);

      doc.setFontSize(18);
      doc.text(`${studentName}'s`, 15, 45);
      doc.setFontSize(16);
      doc.setTextColor(244, 63, 94);
      doc.text(`Personal JLPT ${targetLevel} Mistake & Survival DNA`, 15, 55);

      doc.setTextColor(148, 163, 184);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'normal');
      doc.text(`Generated by Nihomi Learning Memory™ Engine`, 15, 65);
      doc.text(`Ref ID: ${memoryId} | Date: ${new Date().toLocaleDateString()}`, 15, 70);

      // Section 1: Weak Kanji
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(10, 80, pageWidth - 20, 50, 3, 3, 'F');
      doc.setTextColor(12, 24, 43);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('1. YOUR PERSONAL WEAK KANJI DNA', 15, 90);

      let y = 100;
      weakKanji.forEach((k) => {
        doc.setFontSize(9);
        doc.setTextColor(188, 44, 61);
        doc.text(`${k.char} (${k.reading})`, 15, y);
        doc.setTextColor(71, 85, 105);
        doc.setFontSize(7.5);
        doc.setFont('helvetica', 'normal');
        doc.text(`- ${k.meaning}: ${k.tip}`, 45, y);
        y += 8;
      });

      // Section 2: Repeated Grammar Mistakes
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(10, 135, pageWidth - 20, 60, 3, 3, 'F');
      doc.setTextColor(12, 24, 43);
      doc.setFontSize(10);
      doc.setFont('helvetica', 'bold');
      doc.text('2. REPEATED GRAMMAR TRAPS TO AVOID', 15, 145);

      let gy = 154;
      repeatedMistakes.slice(0, 2).forEach((m) => {
        doc.setFontSize(8);
        doc.setTextColor(188, 44, 61);
        doc.setFont('helvetica', 'bold');
        doc.text(`• ${m.topic}`, 15, gy);
        doc.setTextColor(71, 85, 105);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(7);
        doc.text(`Fix: ${m.correctedSentence} | Rule: ${m.rule.slice(0, 45)}...`, 15, gy + 5);
        gy += 14;
      });

      // Footer
      doc.setTextColor(148, 163, 184);
      doc.setFontSize(7);
      doc.text('Certified by Dhaka International Language School & Nihomi Academic Council', pageWidth / 2, 202, { align: 'center' });

      doc.save(`Nihomi-MemoryOS-${studentName.replace(/\s+/g, '_')}-${targetLevel}.pdf`);
    } catch (err) {
      console.error('Failed to generate PDF:', err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="min-h-screen bg-[#F8F9FA] text-[#1A1A1A] py-10 px-4 sm:px-6 lg:px-8" id="memory-os-view">
      <div className="max-w-6xl mx-auto space-y-8">
        {/* Header Hero */}
        <div className="bg-gradient-to-r from-stone-950 via-stone-900 to-stone-950 text-white rounded-3xl p-8 sm:p-12 shadow-xl border border-stone-800 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
          <div className="space-y-3">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-600/30 border border-purple-500/50 text-purple-300 text-xs font-bold">
              <Sparkles className="w-3.5 h-3.5" />
              <span>Nihomi Signature Purple Cow Product</span>
            </div>
            <h1 className="text-3xl sm:text-4xl font-extrabold font-serif tracking-tight">
              Nihomi MemoryOS™
            </h1>
            <p className="text-stone-300 text-xs sm:text-sm max-w-2xl leading-relaxed">
              “Nihomi remembers how you learn.” — Generated entirely from your real study data, quiz errors, and AI Sensei interactions. Download your customized, print-ready A5 Japanese Mistake & Survival DNA Book.
            </p>
          </div>
          <button
            onClick={handleDownloadPDF}
            disabled={isGenerating}
            className="shrink-0 px-6 py-3.5 rounded-2xl bg-red-600 hover:bg-red-700 active:scale-95 text-white font-bold text-xs shadow-lg shadow-red-600/30 flex items-center gap-2 transition-all"
            id="btn-download-memoryos-pdf"
          >
            <Download className="w-4 h-4" />
            <span>{isGenerating ? 'Compiling DNA Book...' : 'Download My A5 Memory Book (PDF)'}</span>
          </button>
        </div>

        {/* Live Learning Memory Preview Container */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
          {/* Left: Book Cover & Preview (7 cols) */}
          <div className="lg:col-span-7 bg-white border border-stone-200 rounded-3xl p-6 sm:p-8 shadow-sm space-y-6">
            <div className="flex items-center justify-between border-b border-stone-100 pb-4">
              <div>
                <span className="text-[11px] font-bold text-red-600 uppercase tracking-wider">Booklet Snapshot</span>
                <h3 className="text-xl font-bold font-serif text-stone-900 mt-0.5">
                  {studentName}'s Personal JLPT {targetLevel} Mistake DNA
                </h3>
              </div>
              <span className="font-mono text-xs font-bold text-stone-400">{memoryId}</span>
            </div>

            {/* Weak Kanji Section */}
            <div className="space-y-3">
              <h4 className="text-xs font-bold uppercase tracking-wider text-stone-500 flex items-center gap-2">
                <Layers className="w-4 h-4 text-red-600" />
                <span>Your Top 3 Weak Kanji (AI Detected from Quizzes)</span>
              </h4>
              <div className="space-y-2.5">
                {weakKanji.map((k) => (
                  <div key={k.char} className="p-4 rounded-2xl bg-stone-50 border border-stone-200 flex items-start gap-4">
                    <div className="w-12 h-12 rounded-xl bg-stone-900 text-white font-serif font-bold text-2xl flex items-center justify-center shrink-0 shadow-xs">
                      {k.char}
                    </div>
                    <div className="space-y-0.5 text-xs">
                      <div className="flex items-center gap-2">
                        <span className="font-bold text-stone-900">{k.reading}</span>
                        <span className="text-stone-500">&bull; {k.meaning}</span>
                        <span className="text-red-600 font-semibold text-[11px] ml-auto">{k.errorRate}</span>
                      </div>
                      <p className="text-stone-600 text-[11px]">
                        <strong>Memory Mnemonic:</strong> {k.tip}
                      </p>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Repeated Grammar Traps */}
            <div className="space-y-3 pt-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-stone-500 flex items-center gap-2">
                <AlertCircle className="w-4 h-4 text-purple-600" />
                <span>Frequent Grammar & Particle Pitfalls</span>
              </h4>
              <div className="space-y-3">
                {repeatedMistakes.map((m, idx) => (
                  <div key={idx} className="p-4 rounded-2xl bg-purple-50/40 border border-purple-200/80 text-xs space-y-1.5">
                    <span className="font-bold text-purple-900 block">{m.topic}</span>
                    <div className="flex items-center gap-3">
                      <span className="line-through text-rose-600 font-serif">{m.failedSentence}</span>
                      <ArrowRight className="w-3.5 h-3.5 text-stone-400" />
                      <span className="font-bold text-emerald-700 font-serif">{m.correctedSentence}</span>
                    </div>
                    <p className="text-stone-600 text-[11px]"><strong>Why:</strong> {m.rule}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Right: Progress DNA & Next Best Action (5 cols) */}
          <div className="lg:col-span-5 space-y-6">
            {/* Progress DNA Breakdown */}
            <div className="bg-white border border-stone-200 rounded-3xl p-6 shadow-sm space-y-4">
              <h3 className="text-base font-bold font-serif text-stone-900 flex items-center gap-2">
                <Zap className="w-4 h-4 text-amber-500" />
                <span>Nihomi Progress DNA™ Matrix</span>
              </h3>
              <div className="space-y-3 text-xs">
                <div>
                  <div className="flex justify-between font-semibold mb-1">
                    <span>Grammar Comprehension</span>
                    <span className="font-bold text-stone-900">76%</span>
                  </div>
                  <div className="w-full h-2 bg-stone-100 rounded-full overflow-hidden">
                    <div className="bg-emerald-500 h-full rounded-full" style={{ width: '76%' }} />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between font-semibold mb-1">
                    <span>Listening & Audio Reflex</span>
                    <span className="font-bold text-stone-900">68%</span>
                  </div>
                  <div className="w-full h-2 bg-stone-100 rounded-full overflow-hidden">
                    <div className="bg-blue-500 h-full rounded-full" style={{ width: '68%' }} />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between font-semibold mb-1">
                    <span>Kanji Retention (Attention Needed)</span>
                    <span className="font-bold text-red-600">54%</span>
                  </div>
                  <div className="w-full h-2 bg-stone-100 rounded-full overflow-hidden">
                    <div className="bg-red-500 h-full rounded-full" style={{ width: '54%' }} />
                  </div>
                </div>

                <div>
                  <div className="flex justify-between font-semibold mb-1">
                    <span>Oral Speaking & Keigo</span>
                    <span className="font-bold text-stone-900">61%</span>
                  </div>
                  <div className="w-full h-2 bg-stone-100 rounded-full overflow-hidden">
                    <div className="bg-amber-500 h-full rounded-full" style={{ width: '61%' }} />
                  </div>
                </div>
              </div>
            </div>

            {/* Next Best Action Card */}
            <div className="bg-gradient-to-br from-red-50 via-amber-50/40 to-rose-50 border border-red-200 rounded-3xl p-6 shadow-sm space-y-3">
              <div className="flex items-center gap-2 text-red-700 font-bold text-xs uppercase tracking-wider">
                <Sparkles className="w-4 h-4" />
                <span>AI Next Best Action</span>
              </div>
              <h4 className="text-base font-bold font-serif text-stone-900">
                10-Minute Kanji Retention Recovery Drill
              </h4>
              <p className="text-xs text-stone-600 leading-relaxed">
                Nihomi detected that you missed 3 Kanji in your last practice. Complete this quick interactive recovery drill to lock them into permanent memory.
              </p>
              <button
                onClick={() => onNavigate('courses')}
                className="w-full py-3 rounded-xl bg-red-600 hover:bg-red-700 text-white font-bold text-xs shadow-sm flex items-center justify-center gap-2 transition-colors"
              >
                <span>Start Recovery Drill</span>
                <ArrowRight className="w-4 h-4" />
              </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};
