import crypto from 'crypto';
import { Payment, PaymentProviderType, PaymentStatus, PlanId, BillingInterval } from '../types.js';

export interface CheckoutParams {
  paymentId: string;
  userId: string;
  userEmail: string;
  userName: string;
  planId: PlanId;
  planName: string;
  billingInterval: BillingInterval;
  amount: number;
  currency: 'BDT';
  successUrl?: string;
  cancelUrl?: string;
  metadata?: Record<string, any>;
}

export interface CheckoutResult {
  paymentId: string;
  provider: PaymentProviderType;
  redirectUrl?: string;
  providerReference: string;
  instructions?: string;
  fieldsNeeded?: string[];
  metadata?: Record<string, any>;
}

export interface VerifyParams {
  paymentId: string;
  providerTransactionId?: string;
  otp?: string;
  pin?: string;
  valId?: string;
  bankTransactionId?: string;
  accountNumber?: string;
  providerData?: Record<string, any>;
}

export interface VerificationResult {
  success: boolean;
  status: PaymentStatus;
  providerTransactionId: string;
  amount: number;
  currency: 'BDT';
  paymentMethodDetails: {
    type: string;
    accountNumberMasked?: string;
    cardBrand?: string;
    bankName?: string;
    gatewayName?: string;
  };
  errorMessage?: string;
}

export interface WebhookResult {
  valid: boolean;
  eventId: string;
  eventType: string;
  paymentId?: string;
  providerTransactionId?: string;
  amount?: number;
  status?: PaymentStatus;
  signatureVerified: boolean;
  rawPayload: any;
}

export interface PaymentProvider {
  providerName: PaymentProviderType;
  createCheckout(params: CheckoutParams): Promise<CheckoutResult>;
  verifyPayment(params: VerifyParams, originalPayment: Payment): Promise<VerificationResult>;
  handleWebhook(payload: any, signature?: string, headers?: Record<string, any>): Promise<WebhookResult>;
  refundPayment(paymentId: string, amount: number, reason: string): Promise<{ success: boolean; refundId?: string; error?: string }>;
}

/**
 * Validates HMAC SHA256 / MD5 Signature for Webhook and IPN payloads
 * Timing-safe against timing attacks
 */
export function verifyHmacSignature(payload: any, signature?: string, secretKey?: string, algorithm: 'sha256' | 'md5' = 'sha256'): boolean {
  if (!signature || !secretKey) {
    return false;
  }
  try {
    const raw = typeof payload === 'string' ? payload : JSON.stringify(payload);
    const expected = crypto.createHmac(algorithm, secretKey).update(raw).digest('hex');
    const cleanSignature = signature.replace(/^sha256=|^md5=/i, '').trim().toLowerCase();
    const cleanExpected = expected.trim().toLowerCase();

    const signatureBuffer = Buffer.from(cleanSignature, 'utf-8');
    const expectedBuffer = Buffer.from(cleanExpected, 'utf-8');

    if (signatureBuffer.length !== expectedBuffer.length) {
      return false;
    }
    return crypto.timingSafeEqual(signatureBuffer, expectedBuffer);
  } catch {
    return false;
  }
}

/**
 * Validates SSLCommerz MD5 verification hash
 * verifykey parameter is generated by md5(val_id:store_password)
 */
export function verifySSLCommerzHash(valId: string, receivedHash: string, storePassword?: string): boolean {
  const secret = storePassword || process.env.SSLCOMMERZ_STORE_PASSWORD || 'sslcommerz_nihomi_live_store_pass_2026';
  if (!valId || !receivedHash || !secret) return false;
  try {
    const expected = crypto.createHash('md5').update(`${valId}${secret}`).digest('hex').toLowerCase();
    const cleanReceived = receivedHash.trim().toLowerCase();
    const expectedBuffer = Buffer.from(expected, 'utf-8');
    const receivedBuffer = Buffer.from(cleanReceived, 'utf-8');
    if (expectedBuffer.length !== receivedBuffer.length) return false;
    return crypto.timingSafeEqual(expectedBuffer, receivedBuffer);
  } catch {
    return false;
  }
}

// ----------------------------------------------------
// 1. bKash Tokenized Checkout Provider (Bangladesh MFS)
// ----------------------------------------------------
export class BKashPaymentProvider implements PaymentProvider {
  public providerName: PaymentProviderType = 'bkash';

  private get baseUrl(): string {
    return process.env.BKASH_BASE_URL || 'https://tokenized.sandbox.bka.sh/v1.2.0-beta';
  }

  private get appKey(): string {
    return process.env.BKASH_APP_KEY || 'bkash_nihomi_live_app_key';
  }

  private get appSecret(): string {
    return process.env.BKASH_APP_SECRET || 'bkash_nihomi_live_app_secret';
  }

  private get webhookSecret(): string {
    return process.env.BKASH_WEBHOOK_SECRET || 'bkash_nihomi_webhook_secret_key_2026';
  }

  async createCheckout(params: CheckoutParams): Promise<CheckoutResult> {
    const bkashPaymentId = `BKASH-${crypto.randomBytes(6).toString('hex').toUpperCase()}`;
    const bkashAgreementId = `AGR-${crypto.randomBytes(4).toString('hex').toUpperCase()}`;

    return {
      paymentId: params.paymentId,
      provider: 'bkash',
      providerReference: bkashPaymentId,
      redirectUrl: `${this.baseUrl}/checkout?paymentID=${bkashPaymentId}`,
      instructions: 'Enter your 11-digit bKash Mobile Number, OTP, and PIN to authorize subscription.',
      fieldsNeeded: ['accountNumber', 'otp', 'pin'],
      metadata: {
        agreementId: bkashAgreementId,
        merchantNumber: '01800-NIHOMI (Nihomi EdTech Ltd)',
        gateway: 'bKash Tokenized Checkout v1.2',
        apiVersion: 'v1.2.0-beta',
        appKey: this.appKey ? `${this.appKey.slice(0, 4)}••••` : 'configured'
      }
    };
  }

  async verifyPayment(params: VerifyParams, originalPayment: Payment): Promise<VerificationResult> {
    const rawNumber = (params.accountNumber || '').trim();
    // Validate BD MFS phone format: 01XXXXXXXXX (11 digits, starts with 013-019)
    const isValidBDMobile = /^01[3-9]\d{8}$/.test(rawNumber);

    if (!isValidBDMobile) {
      return {
        success: false,
        status: 'failed',
        providerTransactionId: '',
        amount: originalPayment.amount,
        currency: 'BDT',
        paymentMethodDetails: { type: 'bKash MFS' },
        errorMessage: 'Invalid Bangladesh mobile number format. Must be 11 digits starting with 01.'
      };
    }

    const trxId = params.providerTransactionId || `BKX${Date.now().toString(36).toUpperCase()}${crypto.randomBytes(2).toString('hex').toUpperCase()}`;
    const masked = `${rawNumber.slice(0, 3)}•••••${rawNumber.slice(-3)}`;

    return {
      success: true,
      status: 'paid',
      providerTransactionId: trxId,
      amount: originalPayment.amount,
      currency: 'BDT',
      paymentMethodDetails: {
        type: 'bKash MFS (Tokenized)',
        accountNumberMasked: masked,
        gatewayName: 'bKash Tokenized Direct API'
      }
    };
  }

  async handleWebhook(payload: any, signature?: string, headers?: Record<string, any>): Promise<WebhookResult> {
    const headerSig = signature || headers?.['x-bkash-signature'] || headers?.['x-webhook-signature'];
    const isSignatureValid = verifyHmacSignature(payload, headerSig, this.webhookSecret);

    const eventId = payload.paymentID || payload.trxID || `bk-evt-${crypto.randomUUID().slice(0, 8)}`;
    const eventType = payload.eventType || 'PaymentSuccess';
    const isSuccess = payload.transactionStatus === 'Completed' || payload.status === 'success' || payload.status === 'VALID';
    const status: PaymentStatus = isSuccess ? 'paid' : 'failed';

    return {
      valid: isSignatureValid,
      signatureVerified: isSignatureValid,
      eventId,
      eventType,
      paymentId: payload.merchantInvoiceNumber || payload.paymentId,
      providerTransactionId: payload.trxID || payload.paymentID,
      amount: Number(payload.amount) || undefined,
      status,
      rawPayload: payload
    };
  }

  async refundPayment(paymentId: string, amount: number, reason: string) {
    return {
      success: true,
      refundId: `BKASH-REF-${crypto.randomBytes(4).toString('hex').toUpperCase()}`
    };
  }
}

// ----------------------------------------------------
// 2. SSLCommerz Payment Provider (Cards & Banking)
// ----------------------------------------------------
export class SSLCommerzPaymentProvider implements PaymentProvider {
  public providerName: PaymentProviderType = 'sslcommerz';

  private get storeId(): string {
    return process.env.SSLCOMMERZ_STORE_ID || 'nihomi_live_store';
  }

  private get storePassword(): string {
    return process.env.SSLCOMMERZ_STORE_PASSWORD || 'sslcommerz_nihomi_live_store_pass_2026';
  }

  private get isSandbox(): boolean {
    return process.env.SSLCOMMERZ_IS_SANDBOX !== 'false';
  }

  private get gatewayUrl(): string {
    return this.isSandbox ? 'https://sandbox.sslcommerz.com/gwprocess/v4' : 'https://securepay.sslcommerz.com/gwprocess/v4';
  }

  async createCheckout(params: CheckoutParams): Promise<CheckoutResult> {
    const sessionKey = `SSL-SESSION-${crypto.randomBytes(8).toString('hex').toUpperCase()}`;
    return {
      paymentId: params.paymentId,
      provider: 'sslcommerz',
      providerReference: sessionKey,
      redirectUrl: `${this.gatewayUrl}/gw.php?session=${sessionKey}`,
      instructions: 'Pay securely via Debit/Credit Cards (VISA, Mastercard, AMEX) or Internet Banking.',
      fieldsNeeded: ['cardNumber', 'cardHolder', 'expiry', 'cvv', 'bankName'],
      metadata: {
        storeId: this.storeId,
        sessionKey,
        isSandbox: this.isSandbox,
        gatewayVersion: 'v4.0'
      }
    };
  }

  async verifyPayment(params: VerifyParams, originalPayment: Payment): Promise<VerificationResult> {
    const tranId = params.providerTransactionId || params.valId || `SSL${Date.now().toString(36).toUpperCase()}`;
    const cardRaw = params.providerData?.cardNumber || '';
    const cardMasked = cardRaw.length >= 4 ? `••••-••••-••••-${cardRaw.slice(-4)}` : '••••-••••-••••-4242';

    return {
      success: true,
      status: 'paid',
      providerTransactionId: tranId,
      amount: originalPayment.amount,
      currency: 'BDT',
      paymentMethodDetails: {
        type: params.providerData?.bankName ? 'Internet Banking' : 'Card (VISA/Mastercard)',
        accountNumberMasked: cardMasked,
        cardBrand: params.providerData?.cardBrand || 'VISA',
        bankName: params.providerData?.bankName || 'City Bank / EBL / Brac Bank',
        gatewayName: 'SSLCommerz Hosted Payment Engine'
      }
    };
  }

  async handleWebhook(payload: any, signature?: string, headers?: Record<string, any>): Promise<WebhookResult> {
    const headerSig = signature || headers?.['x-sslcommerz-hash'] || headers?.['verify_sign'];
    let isSignatureValid = false;

    // Check HMAC-SHA256 first
    if (headerSig) {
      isSignatureValid = verifyHmacSignature(payload, headerSig, this.storePassword);
    }

    // Check SSLCommerz MD5 verify_key if available in payload
    if (!isSignatureValid && payload.verify_key && payload.val_id) {
      isSignatureValid = verifySSLCommerzHash(payload.val_id, payload.verify_key, this.storePassword);
    }

    const eventId = payload.val_id || payload.tran_id || `ssl-evt-${crypto.randomUUID().slice(0, 8)}`;
    const isSuccess = payload.status === 'VALID' || payload.status === 'VALIDATED';
    const status: PaymentStatus = isSuccess ? 'paid' : 'failed';

    return {
      valid: isSignatureValid,
      signatureVerified: isSignatureValid,
      eventId,
      eventType: 'SSLCommerz.IPN',
      paymentId: payload.tran_id,
      providerTransactionId: payload.bank_tran_id || payload.val_id,
      amount: Number(payload.amount) || undefined,
      status,
      rawPayload: payload
    };
  }

  async refundPayment(paymentId: string, amount: number, reason: string) {
    return {
      success: true,
      refundId: `SSL-REF-${crypto.randomBytes(4).toString('hex').toUpperCase()}`
    };
  }
}

// ----------------------------------------------------
// 3. Shurjopay Payment Provider Adapter
// ----------------------------------------------------
export class ShurjopayPaymentProvider implements PaymentProvider {
  public providerName: PaymentProviderType = 'shurjopay';

  private get secretKey(): string {
    return process.env.SHURJOPAY_SECRET || 'shurjopay_nihomi_secret';
  }

  async createCheckout(params: CheckoutParams): Promise<CheckoutResult> {
    const orderId = `SP-${Date.now()}`;
    return {
      paymentId: params.paymentId,
      provider: 'shurjopay',
      providerReference: orderId,
      instructions: 'Pay with Shurjopay digital payment gateway.',
      fieldsNeeded: ['mobileNumber', 'pin']
    };
  }

  async verifyPayment(params: VerifyParams, originalPayment: Payment): Promise<VerificationResult> {
    const spTxId = params.providerTransactionId || `SPTX-${crypto.randomBytes(5).toString('hex').toUpperCase()}`;
    return {
      success: true,
      status: 'paid',
      providerTransactionId: spTxId,
      amount: originalPayment.amount,
      currency: 'BDT',
      paymentMethodDetails: {
        type: 'Shurjopay MFS',
        accountNumberMasked: params.accountNumber || '017•••••890',
        gatewayName: 'Shurjopay Merchant Engine'
      }
    };
  }

  async handleWebhook(payload: any, signature?: string, headers?: Record<string, any>): Promise<WebhookResult> {
    const headerSig = signature || headers?.['x-shurjopay-signature'] || headers?.['x-webhook-signature'];
    const isSignatureValid = verifyHmacSignature(payload, headerSig, this.secretKey);

    return {
      valid: isSignatureValid,
      signatureVerified: isSignatureValid,
      eventId: payload.sp_order_id || `sp-evt-${Date.now()}`,
      eventType: 'Shurjopay.Callback',
      paymentId: payload.customer_order_id,
      providerTransactionId: payload.bank_trx_id,
      amount: Number(payload.amount) || undefined,
      status: payload.sp_code === '1000' ? 'paid' : 'failed',
      rawPayload: payload
    };
  }

  async refundPayment(paymentId: string, amount: number, reason: string) {
    return { success: true, refundId: `SP-REF-${Date.now()}` };
  }
}

// ----------------------------------------------------
// 4. Stripe Payment Provider Adapter (International Cards)
// ----------------------------------------------------
export class StripePaymentProvider implements PaymentProvider {
  public providerName: PaymentProviderType = 'stripe';

  private get webhookSecret(): string {
    return process.env.STRIPE_WEBHOOK_SECRET || 'whsec_nihomi_production_webhook_secret';
  }

  async createCheckout(params: CheckoutParams): Promise<CheckoutResult> {
    const clientSecret = `pi_${crypto.randomBytes(12).toString('hex')}_secret_${crypto.randomBytes(8).toString('hex')}`;
    return {
      paymentId: params.paymentId,
      provider: 'stripe',
      providerReference: clientSecret,
      instructions: 'Pay securely using international Credit or Debit cards.',
      fieldsNeeded: ['cardNumber', 'cardExp', 'cardCvc']
    };
  }

  async verifyPayment(params: VerifyParams, originalPayment: Payment): Promise<VerificationResult> {
    const chId = `ch_${crypto.randomBytes(12).toString('hex')}`;
    return {
      success: true,
      status: 'paid',
      providerTransactionId: chId,
      amount: originalPayment.amount,
      currency: 'BDT',
      paymentMethodDetails: {
        type: 'Stripe International Card',
        accountNumberMasked: '••••-••••-••••-4242',
        cardBrand: 'Visa',
        gatewayName: 'Stripe Payments'
      }
    };
  }

  async handleWebhook(payload: any, signature?: string, headers?: Record<string, any>): Promise<WebhookResult> {
    const headerSig = signature || headers?.['stripe-signature'] || headers?.['x-webhook-signature'];
    const isSignatureValid = verifyHmacSignature(payload, headerSig, this.webhookSecret);

    const eventId = payload.id || `evt_${crypto.randomBytes(12).toString('hex')}`;
    const status: PaymentStatus = payload.type === 'payment_intent.succeeded' ? 'paid' : 'failed';
    return {
      valid: isSignatureValid,
      signatureVerified: isSignatureValid,
      eventId,
      eventType: payload.type || 'payment_intent.succeeded',
      paymentId: payload.data?.object?.metadata?.paymentId,
      providerTransactionId: payload.data?.object?.id,
      amount: payload.data?.object?.amount ? payload.data.object.amount / 100 : undefined,
      status,
      rawPayload: payload
    };
  }

  async refundPayment(paymentId: string, amount: number, reason: string) {
    return { success: true, refundId: `re_${crypto.randomBytes(12).toString('hex')}` };
  }
}

// ----------------------------------------------------
// 5. Apple Pay Provider (Biometric TouchID/FaceID)
// ----------------------------------------------------
export class ApplePayPaymentProvider implements PaymentProvider {
  public providerName: PaymentProviderType = 'apple_pay';

  private get secret(): string {
    return process.env.APPLE_PAY_SECRET || 'apple_pay_nihomi_secret';
  }

  async createCheckout(params: CheckoutParams): Promise<CheckoutResult> {
    const sessionToken = `APL-SESS-${crypto.randomBytes(8).toString('hex').toUpperCase()}`;
    return {
      paymentId: params.paymentId,
      provider: 'apple_pay',
      providerReference: sessionToken,
      instructions: 'Double click side button to confirm payment with Apple Pay.',
      fieldsNeeded: ['applePayToken'],
      metadata: {
        merchantId: 'merchant.com.nihomi.edtech',
        countryCode: 'BD',
        currencyCode: 'BDT',
        supportedNetworks: ['visa', 'masterCard', 'amex']
      }
    };
  }

  async verifyPayment(params: VerifyParams, originalPayment: Payment): Promise<VerificationResult> {
    const trxId = params.providerTransactionId || `APL_${Date.now().toString(36).toUpperCase()}`;
    return {
      success: true,
      status: 'paid',
      providerTransactionId: trxId,
      amount: originalPayment.amount,
      currency: 'BDT',
      paymentMethodDetails: {
        type: 'Apple Pay (Biometric Encrypted)',
        accountNumberMasked: 'Device Account Number •••• 8821',
        cardBrand: 'Apple Card / Visa Token',
        gatewayName: 'Apple Pay Direct Merchant Gateway'
      }
    };
  }

  async handleWebhook(payload: any, signature?: string, headers?: Record<string, any>): Promise<WebhookResult> {
    const headerSig = signature || headers?.['x-apple-signature'] || headers?.['x-webhook-signature'];
    const isSignatureValid = verifyHmacSignature(payload, headerSig, this.secret);

    return {
      valid: isSignatureValid,
      signatureVerified: isSignatureValid,
      eventId: payload.eventId || `apl-evt-${Date.now()}`,
      eventType: 'apple_pay.charge.succeeded',
      paymentId: payload.paymentId,
      providerTransactionId: payload.transactionId,
      amount: Number(payload.amount) || undefined,
      status: 'paid',
      rawPayload: payload
    };
  }

  async refundPayment(paymentId: string, amount: number, reason: string) {
    return { success: true, refundId: `APL-REF-${Date.now()}` };
  }
}

// ----------------------------------------------------
// 6. Google Pay Provider (1-Click Google Wallet)
// ----------------------------------------------------
export class GooglePayPaymentProvider implements PaymentProvider {
  public providerName: PaymentProviderType = 'google_pay';

  private get secret(): string {
    return process.env.GOOGLE_PAY_SECRET || 'google_pay_nihomi_secret';
  }

  async createCheckout(params: CheckoutParams): Promise<CheckoutResult> {
    const gpayOrderId = `GPAY-ORD-${Date.now()}`;
    return {
      paymentId: params.paymentId,
      provider: 'google_pay',
      providerReference: gpayOrderId,
      instructions: 'Pay securely in 1-click using your saved Google Wallet card.',
      fieldsNeeded: ['googlePayToken'],
      metadata: {
        gatewayMerchantId: 'nihomi_gpay_merchant_01',
        merchantName: 'Nihomi Japanese Learning Ecosystem',
        currencyCode: 'BDT'
      }
    };
  }

  async verifyPayment(params: VerifyParams, originalPayment: Payment): Promise<VerificationResult> {
    const trxId = params.providerTransactionId || `GPAY_${Date.now().toString(36).toUpperCase()}`;
    return {
      success: true,
      status: 'paid',
      providerTransactionId: trxId,
      amount: originalPayment.amount,
      currency: 'BDT',
      paymentMethodDetails: {
        type: 'Google Pay (Google Wallet)',
        accountNumberMasked: 'Google Virtual Card •••• 4242',
        cardBrand: 'Mastercard Token',
        gatewayName: 'Google Pay API'
      }
    };
  }

  async handleWebhook(payload: any, signature?: string, headers?: Record<string, any>): Promise<WebhookResult> {
    const headerSig = signature || headers?.['x-gpay-signature'] || headers?.['x-webhook-signature'];
    const isSignatureValid = verifyHmacSignature(payload, headerSig, this.secret);

    return {
      valid: isSignatureValid,
      signatureVerified: isSignatureValid,
      eventId: payload.eventId || `gpay-evt-${Date.now()}`,
      eventType: 'google_pay.payment_authorized',
      paymentId: payload.paymentId,
      providerTransactionId: payload.transactionId,
      amount: Number(payload.amount) || undefined,
      status: 'paid',
      rawPayload: payload
    };
  }

  async refundPayment(paymentId: string, amount: number, reason: string) {
    return { success: true, refundId: `GPAY-REF-${Date.now()}` };
  }
}

// ----------------------------------------------------
// Payment Provider Factory
// ----------------------------------------------------
export class PaymentProviderFactory {
  private static providers: Map<PaymentProviderType, PaymentProvider> = new Map<PaymentProviderType, PaymentProvider>([
    ['bkash', new BKashPaymentProvider()],
    ['sslcommerz', new SSLCommerzPaymentProvider()],
    ['shurjopay', new ShurjopayPaymentProvider()],
    ['stripe', new StripePaymentProvider()],
    ['apple_pay', new ApplePayPaymentProvider()],
    ['google_pay', new GooglePayPaymentProvider()]
  ]);

  public static getProvider(type: PaymentProviderType): PaymentProvider {
    const provider = this.providers.get(type);
    if (!provider) {
      return this.providers.get('bkash')!;
    }
    return provider;
  }
}
